spring:
  datasource:
    url: jdbc:h2:mem:db_notifications
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

services:
  user-service:
    url: http://localhost:8081

eureka:
  instance:
    prefer-ip-address: true

spring:
  flyway:
    enabled: false