spring:
  application:
    name: audit-service
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.hateoas.HateoasAutoConfiguration

server:
  port: 8090

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}