spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/books/**

        - id: review-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/reviews/**

        - id: reading-list-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/lists/**

        - id: social-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/social/**
